### ISSUE TITLE
Installing latest version

### ISSUE THREAD

**Issue by mattkemp** [missionpinball/mpf-ls#10]
Following the readme I've installed using

```
pip3 install mpf-language-server
```

which gets me version 0.54.2 which still has errors for standalone show files:

```
Internal error while verifying: 'int' object has no attribute 'split' Traceback (most recent call last):
  File "c:\users\matt\mpfenv\lib\site-packages\mpfls\mpf_ls.py", line 1267, in lint
    diagnostics = self._walk_diagnostics_root(document, document.config_roundtrip)
  File "c:\users\matt\mpfenv\lib\site-packages\mpfls\mpf_ls.py", line 975, in _walk_diagnostics_root
    root_spec = self._get_spec(key)
  File "c:\users\matt\mpfenv\lib\site-packages\mpfls\mpf_ls.py", line 1077, in _get_spec
    spec_names = spec_name_str.split(",")
AttributeError: 'int' object has no attribute 'split'
mpf-ls(998)
```

I installed the dev branch using

```
pip3 install git+https://github.com/missionpinball/mpf-ls.git@dev
```

so `pip3 list` now shows the version as `mpf-language-server     0.55.0.dev1+8.g4d9055d` and the code matches.

I've realised as I've worked through this that the dev branch just hasn't been released in a while, and standalone show files are still broken. I'll leave this here for people who want to know how to get the latest and raise another issue.

**Comment by MistyKoiFish** [comment]
I also did end up following the guide but ran into some issues because the extension in VS Code keep crashing every time it tried to run. I ended up following your instructions but I ended up getting "mpf-language-server   0.55.0.dev1+22.g3157dff" after I typed in pip3 list. I used the dev branch link you posted but I still ended up getting that output. Do you possibly have an explanation or solution to this issue?
