### ISSUE TITLE
mpf language server

### ISSUE THREAD

**Issue by worldpeace-germany** [missionpinball/mpf-ls#12]
Hi,

I am having trouble getting the mpfls to run. I am able to run mpf in my machine folder, but not outside of it, not sure if that matters and is a prerequisite. I saw in the video tutorial that I should be able to run mpfls after installation, when I run mpfls (regardless in what folder) I get

```
mpfls
Traceback (most recent call last):
  File "/home/dev-user/.local/bin/mpfls", line 11, in <module>
    load_entry_point('mpf-language-server==0.54.2', 'console_scripts', 'mpfls')()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/dev-user/.local/lib/python3.9/site-packages/mpfls/__main__.py", line 7, in <module>
    from .mpf_ls import start_io_lang_server, start_tcp_lang_server, MPFLanguageServer
  File "/home/dev-user/.local/lib/python3.9/site-packages/mpfls/mpf_ls.py", line 12, in <module>
    from mpf.core.config_processor import ConfigProcessor
ModuleNotFoundError: No module named 'mpf'
```

What else as a prerequisite do I need?

mpf is
```
mpf --version
MPF v0.56.0-dev33
```

Again not sure if it matters, I have multiple versions of python on my box, so I need to run python3.9 and pip3.9 as command and not python3 or pip3.

Thanks!

**Comment by Pucksnok** [comment]
Came here to say I have what I believe might be the same error, not sure, Windows 11, Python 3.9, MPF v0.56.0-dev33.
Did you get it running?

C:\mpfls
Traceback (most recent call last):
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python39\Scripts\mpfls-script.py", line 33, in <module>
    sys.exit(load_entry_point('mpf-language-server==0.54.2', 'console_scripts', 'mpfls')())
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python39\Scripts\mpfls-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfls\__main__.py", line 7, in <module>
    from .mpf_ls import start_io_lang_server, start_tcp_lang_server, MPFLanguageServer
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfls\mpf_ls.py", line 12, in <module>
    from mpf.core.config_processor import ConfigProcessor
ModuleNotFoundError: No module named 'mpf'

**Comment by worldpeace-germany** [comment]
I still have no solution. I still hope someone can help, until then I am editing my config files in a plain text editor. I am glad you post it though, it shows that the problem can occur on Windows and on Linux.

**Comment by Pucksnok** [comment]
A update for my windows installation, if I start vscode from a command prompt in my machine directory it works!!

Example: start cmd, cd mymachinedirectory, type code to start vscode from cmd. It then works with the language server!
Will make a new shortcut and make it open from the machine directory.

**Comment by worldpeace-germany** [comment]
I spent now some time on it and was able to get it to work. I believe there is some bug in the installation routine or I have missed some step in the installation which I am totally not aware of. 

If one of the developers reads this, I am more than happy to test to improve either some part of the software or the installation guide if I really have missed something. 

Anyways, here is what I did:

In this folder

`/home/dev-user/.local/lib/python3.9/site-packages/`

I have all kind of python packages, among them `mpf` and `mpfmc` (for the non-python persons: both are folders with lots of files in there)

Then I have this folder

`/home/dev-user/.local/pipx/venvs/mpf/lib/python3.9/site-packages/`

where `mpfls` (again a folder with lots of files) is located, but there are no folders named `mpf` and `mpfmc`! I copied both of these folder from the first location above into that directory here. That fixes the issue for me.

I have to admit that my daily job is _not_ python development and I am unaware of what pipx is doing in detail and what in the installation went wrong.

@Pucksnok  I got a notification email from you that you found the issue for you, but I am not seeing that post on Github. Not sure what the reason is,  I only can assume that you have deleted it. If you still have the same issue, maybe the above helps you. Would be nice if you could report back what  directory structure you have and what helped or not helped to solve your problem.

**Comment by Pucksnok** [comment]
@worldpeace-germany I did a post but it turned out to be all wrong and not working...

I run Windows and my C:\Users\%username%\.local\pipx\venvs\mpf\Lib\site-packages do have both mpfls and mpf folder inside it. You wanted me to check it up a bit more.

I did start to read up a bit on pipx to understand what happens when installing using pipx. I then followed the installation guide for installation from start to finish but got the same error when running mpfls. Looking in the logs file it do install to the same virtual environment called mpf.


1. Installing MPF with: pipx install "mpf[cli]" --verbose --include-deps
2. Installing MPF MC with: pipx inject mpf mpf-mc --verbose --include-deps --include-apps
3. Installing MPF-LS with: pipx inject mpf mpf-language-server --pip-args=--pre --verbose --include-deps --include-apps
4. Both MPF MC and MPF-LS are injected into the same virtual environment according to both log files and the output in the command prompt.
5. The virtual environment mpf located at C:\Users\Johan\.local\pipx\venvs\mpf, if I check C:\Users\Johan\.local\pipx\venvs\mpf\Lib\site-packages all three folders are there, mpf, mpfmc and mpfls.
6. Running mpf and mpfmc works as it should. mpfls doesn't.
Output as following.

Traceback (most recent call last):
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python39\Scripts\mpfls-script.py", line 33, in <module>
    sys.exit(load_entry_point('mpf-language-server==0.54.2', 'console_scripts', 'mpfls')())
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python39\Scripts\mpfls-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfls\__main__.py", line 7, in <module>
    from .mpf_ls import start_io_lang_server, start_tcp_lang_server, MPFLanguageServer
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python39\lib\site-packages\mpfls\mpf_ls.py", line 12, in <module>
    from mpf.core.config_processor import ConfigProcessor
ModuleNotFoundError: No module named 'mpf'

7. I now see it doesn't run from the correct location, I did once downgrade to python 3.8 to match my Linux machine which will run inside the pinball machine. python --version shows 3.8.6, python 3.9 is also installed. It appears that pipx is installed with Python 3.9 and never installed with 3.8, so everything installed with pipx is running python 3.9 even thou my python --version shows 3.8.6. I know learnt how it works so this mistake will not be done again.
8. I removed the path for Python 3.9 and rebooted. mpf no longer works, python --version still works, pipx doesn't work. I been running MPF in 3.9 all the time when running mpf. :D
9. Time to uninstall everything Python and start over just to be sure.


And here we go from scratch....

1. Manually removed all Python related stuff in path. Uninstalled Python 3.8 and 3.9.
2. Python 3.9.13 installed. No other Python installed.
3. path added so reboot needed (or log in log out should work I believe, still rebooted!).
4. python --version show 3.9.13, 
5. time to install everything.
6. pipx install "mpf[cli]" --verbose --include-deps
7. pipx inject mpf mpf-mc --verbose --include-deps --include-apps
8. pipx inject mpf mpf-language-server --pip-args=--pre --verbose --include-deps --include-apps
9. Trying mpf with my machine, working as it should. 
10. Trying to start mpfls manually from cmd, behold, it works.
11. Going into vscode, no errors in the mpfls addon!
12. Seems to give me suggestions when typing, stuff I didn't used anywhere. But getting "expected a dictionary" on everything I try so no real help with syntax etc. Not sure how it's supposed to work.

Progress at least, addon in visual studio code (vscode) starts and mpfls seems to start, I did think it would help with syntax etc. but maybe I had unrealistic expectations, or something is wrong!? :D 
I now at least understand pipx and python installations a lot better and I now know my downgrade to 3.8 for troubleshooting really didn't do anything. Learning every day.

**Comment by worldpeace-germany** [comment]
Created now an empty virtual machine to give it another test, here it worked out fine. No idea what went wrong before and why these packages have been missing. For now I will then close that issue report.
